package com.pokemons.core.ui.theme

import androidx.compose.ui.graphics.Color

internal val ColorBase1 = Color(COLOR_BASE_1)
internal val ColorBase2 = Color(COLOR_BASE_2)
internal val ColorBase3 = Color(COLOR_BASE_3)
internal val ColorBase4 = Color(COLOR_BASE_4)
internal val ColorBase5 = Color(COLOR_BASE_5)
internal val ColorBase6 = Color(COLOR_BASE_6)
internal val ColorBase7 = Color(COLOR_BASE_7)
internal val ColorBase8 = Color(COLOR_BASE_8)
internal val ColorBase9 = Color(COLOR_BASE_9)
internal val ColorBase10 = Color(COLOR_BASE_10)
internal val ColorBase11 = Color(COLOR_BASE_11)
internal val ColorBase12 = Color(COLOR_BASE_12)
internal val ColorBase13 = Color(COLOR_BASE_13)
internal val ColorBase14 = Color(COLOR_BASE_14)
internal val ColorBase15 = Color(COLOR_BASE_15)
internal val ColorBase16 = Color(COLOR_BASE_16)
internal val ColorBase17 = Color(COLOR_BASE_17)
internal val ColorBase18 = Color(COLOR_BASE_18)
internal val ColorBase19 = Color(COLOR_BASE_19)
internal val ColorBase20 = Color(COLOR_BASE_20)
internal val ColorBase21 = Color(COLOR_BASE_21)
internal val ColorBase22 = Color(COLOR_BASE_22)
internal val ColorBase23 = Color(COLOR_BASE_23)

internal val ColorBrand1 = Color(COLOR_BRAND_1)
internal val ColorBrand2 = Color(COLOR_BRAND_2)
internal val ColorBrand3 = Color(COLOR_BRAND_3)

internal val ColorBrandGreen1 = Color(COLOR_BRAND_GREEN_1)
internal val ColorBrandGreen2 = Color(COLOR_BRAND_GREEN_2)
internal val ColorBrandGreen3 = Color(COLOR_BRAND_GREEN_3)

internal val ColorRed1 = Color(COLOR_RED_1)
internal val ColorRed2 = Color(COLOR_RED_2)
internal val ColorRed3 = Color(COLOR_RED_3)
internal val ColorRed4 = Color(COLOR_RED_4)

internal val ColorOrange1 = Color(COLOR_ORANGE_1)
internal val ColorOrange2 = Color(COLOR_ORANGE_2)
internal val ColorOrange3 = Color(COLOR_ORANGE_3)
internal val ColorOrange4 = Color(COLOR_ORANGE_4)
internal val ColorOrange5 = Color(COLOR_ORANGE_5)
internal val ColorOrange6 = Color(COLOR_ORANGE_6)
internal val ColorOrange7 = Color(COLOR_ORANGE_7)

internal val ColorGreen1 = Color(COLOR_GREEN_1)
internal val ColorGreen2 = Color(COLOR_GREEN_2)
internal val ColorGreen3 = Color(COLOR_GREEN_3)
internal val ColorGreen4 = Color(COLOR_GREEN_4)
internal val ColorGreen5 = Color(COLOR_GREEN_5)
internal val ColorGreen6 = Color(COLOR_GREEN_6)
