package com.pokemons.core.ui.theme

internal val LightVioletColorPalette = AppColors(
  isLight = true,
  backgroundMain = ColorBase4,
  backgroundSecondary = ColorBase1,
  backgroundTertiary = ColorBase14,
  backgroundQuaternary = ColorBase1.copy(alpha = 0.8f),
  contentPrimary = ColorBase1,
  contentSecondary = ColorBase3,
  contentSecondaryV2 = ColorBase22,
  contentTertiary = ColorBase5,
  contentButton = ColorBase1,
  textPrimary = ColorBase15,
  textPrimaryButton = ColorBase1,
  textSecondary = ColorBase7,
  textTertiary = ColorBase15,
  brandColorAccent = ColorBrand1,
  brandBackground = ColorBrand2,
  brandAccentBackground = ColorBrand2,
  indicatorContentNegative = ColorRed2,
  indicatorBackgroundNegative = ColorRed3,
  indicatorContentNegativeLight = ColorRed2,
  indicatorContentAttention = ColorOrange3,
  indicatorBackgroundAttention = ColorOrange2,
  indicatorContentPositive = ColorGreen1,
  indicatorBackgroundPositive = ColorGreen3,
  indicatorContentRating = ColorOrange1,
  indicatorBackgroundRating = ColorOrange6,
  shadowColor = ColorBase15,
  overlay = ColorBase17.copy(alpha = 0.4f),
  indicatorBackgroundTraffic = ColorGreen5.copy(alpha = 0.8f),
  primaryMain = ColorBase1.copy(alpha = 0.8f),
  skeletonBase = ColorBase20,
  skeletonHighlight = ColorBase7,
  searchBar = ColorBase21,
  iconRouting = ColorBase1.copy(alpha = 0.5f)
)

internal val DarkVioletColorPalette = AppColors(
  isLight = false,
  backgroundMain = ColorBase16,
  backgroundSecondary = ColorBase13,
  backgroundTertiary = ColorBase14,
  backgroundQuaternary = ColorBase1.copy(alpha = 0.8f),
  contentPrimary = ColorBase12,
  contentSecondary = ColorBase11,
  contentSecondaryV2 = ColorBase23,
  contentTertiary = ColorBase8,
  contentButton = ColorBase9,
  textPrimary = ColorBase2,
  textPrimaryButton = ColorBase1,
  textSecondary = ColorBase6,
  textTertiary = ColorBase15,
  brandColorAccent = ColorBrand1,
  brandBackground = ColorBrand3,
  brandAccentBackground = ColorBrand2,
  indicatorContentNegative = ColorRed1,
  indicatorBackgroundNegative = ColorRed4,
  indicatorContentAttention = ColorOrange4,
  indicatorBackgroundAttention = ColorOrange5,
  indicatorContentNegativeLight = ColorRed2,
  indicatorContentPositive = ColorGreen2,
  indicatorBackgroundPositive = ColorGreen4,
  indicatorContentRating = ColorOrange3,
  indicatorBackgroundRating = ColorOrange7,
  shadowColor = ColorBase17,
  overlay = ColorBase17.copy(alpha = 0.4f),
  indicatorBackgroundTraffic = ColorGreen6.copy(alpha = 0.8f),
  primaryMain = ColorBase17.copy(alpha = 0.8f),
  skeletonBase = ColorBase18,
  skeletonHighlight = ColorBase19,
  searchBar = ColorBase10,
  iconRouting = ColorBase1.copy(alpha = 0.5f)
)

internal val LightGreenColorPalette = AppColors(
  isLight = true,
  backgroundMain = ColorBase4,
  backgroundSecondary = ColorBase1,
  backgroundTertiary = ColorBase14,
  backgroundQuaternary = ColorBase1.copy(alpha = 0.8f),
  contentPrimary = ColorBase1,
  contentSecondary = ColorBase3,
  contentSecondaryV2 = ColorBase22,
  contentTertiary = ColorBase5,
  contentButton = ColorBase1,
  textPrimary = ColorBase15,
  textPrimaryButton = ColorBase1,
  textSecondary = ColorBase7,
  textTertiary = ColorBase15,
  brandColorAccent = ColorBrandGreen1,
  brandBackground = ColorBrandGreen2,
  brandAccentBackground = ColorBrand2,
  indicatorContentNegative = ColorRed2,
  indicatorBackgroundNegative = ColorRed3,
  indicatorContentNegativeLight = ColorRed2,
  indicatorContentAttention = ColorOrange3,
  indicatorBackgroundAttention = ColorOrange2,
  indicatorContentPositive = ColorGreen1,
  indicatorBackgroundPositive = ColorGreen3,
  indicatorContentRating = ColorOrange1,
  indicatorBackgroundRating = ColorOrange6,
  shadowColor = ColorBase15,
  overlay = ColorBase17.copy(alpha = 0.4f),
  indicatorBackgroundTraffic = ColorGreen5.copy(alpha = 0.8f),
  primaryMain = ColorBase1.copy(alpha = 0.8f),
  skeletonBase = ColorBase20,
  skeletonHighlight = ColorBase7,
  searchBar = ColorBase21,
  iconRouting = ColorBase1.copy(alpha = 0.5f)
)

internal val DarkGreenColorPalette = AppColors(
  isLight = false,
  backgroundMain = ColorBase16,
  backgroundSecondary = ColorBase13,
  backgroundTertiary = ColorBase14,
  backgroundQuaternary = ColorBase1.copy(alpha = 0.8f),
  contentPrimary = ColorBase12,
  contentSecondary = ColorBase11,
  contentSecondaryV2 = ColorBase23,
  contentTertiary = ColorBase8,
  contentButton = ColorBase9,
  textPrimary = ColorBase2,
  textPrimaryButton = ColorBase1,
  textSecondary = ColorBase6,
  textTertiary = ColorBase15,
  brandColorAccent = ColorBrandGreen1,
  brandBackground = ColorBrandGreen3,
  brandAccentBackground = ColorBrand2,
  indicatorContentNegative = ColorRed1,
  indicatorBackgroundNegative = ColorRed4,
  indicatorContentAttention = ColorOrange4,
  indicatorBackgroundAttention = ColorOrange5,
  indicatorContentNegativeLight = ColorRed2,
  indicatorContentPositive = ColorGreen2,
  indicatorBackgroundPositive = ColorGreen4,
  indicatorContentRating = ColorOrange3,
  indicatorBackgroundRating = ColorOrange7,
  shadowColor = ColorBase17,
  overlay = ColorBase17.copy(alpha = 0.4f),
  indicatorBackgroundTraffic = ColorGreen6.copy(alpha = 0.8f),
  primaryMain = ColorBase17.copy(alpha = 0.8f),
  skeletonBase = ColorBase18,
  skeletonHighlight = ColorBase19,
  searchBar = ColorBase10,
  iconRouting = ColorBase1.copy(alpha = 0.5f)
)
